# Create a new event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Evento para quem é apaixonado por programação",
  "maxAttendees": 100
}

###

# Update event
PUT http://localhost:3333/events/bd7e0d2f-2b9f-40a9-8fa6-0dfcaa0fae13
Content-Type: application/json

{
  "title": "NLW Unite",
  "details": "Evento quem é avançado na programação"
}

###

# Remove a specific event by id
DELETE http://localhost:3333/events/c69a43c6-e7e7-4b42-9128-228db125a886

###

# Get specific event by id
GET http://localhost:3333/events/bd7e0d2f-2b9f-40a9-8fa6-0dfcaa0fae13

###

# Get all events
GET http://localhost:3333/events