# Create a new attendee
POST http://localhost:3333/attendees
Content-Type: application/json

{
  "name": "Jhon Doe",
  "email": "jhon.doe@email.com",
  "eventId": "0fd1dcb8-1721-458e-a391-f029ea78b204"
}

###

# Update attendee
PUT http://localhost:3333/attendees/1
Content-Type: application/json

{
  "name": "Jhon Doe 2",
  "email": "jhon.doe2@gmail.com"
}

###

# Remove a specific attendee by id
DELETE http://localhost:3333/attendees/1

###

# Get specific attendee by id
GET http://localhost:3333/attendees/1

###

# Get all attendees
GET http://localhost:3333/attendees