# Register a new attendee for an event
POST http://localhost:3333/events/0a38f029-359e-46a6-a073-de23bb4dcce9/attendees
Content-Type: application/json

{
  "name": "Joaozin",
  "email": "panizio@gmail.com"
}

###

# Update attendee
PUT http://localhost:3333/attendees/19
Content-Type: application/json

{
  "name": "Jhon Doe",
  "email": "hjbjhbbkjbn@gmail.com"
}

###

# Remove a specific attendee by id
DELETE http://localhost:3333/attendees/19

###

# Get specific attendee by id
GET http://localhost:3333/attendees/19