# Create a new event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Evento para quem é apaixonado por programação",
  "maxAttendees": 100
}

###

# Update event
PUT http://localhost:3333/events/0fd1dcb8-1721-458e-a391-f029ea78b204
Content-Type: application/json

{
  "title": "NLW Unite",
  "details": "Evento quem é avançado na programação"
}

###

# Remove a specific event by id
DELETE http://localhost:3333/events/0fd1dcb8-1721-458e-a391-f029ea78b204

###

# Get specific event by id
GET http://localhost:3333/events/0fd1dcb8-1721-458e-a391-f029ea78b204

###

# Get all events
GET http://localhost:3333/events