# Create a new event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite2 Summit dddd",
  "details": "Evento para quem é apaixonado por programação",
  "maxAttendees": 100
}

###

# Update event
PUT http://localhost:3333/events/d298f36e-9453-41bb-962b-212308365f62
Content-Type: application/json

{
  "title": "NLW Unite",
  "details": "details"
}

###

# Remove a specific event by id
DELETE http://localhost:3333/events/d298f36e-9453-41bb-962b-212308365f62

###

# Get specific event by id
GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33

###

# Get all events
GET http://localhost:3333/events

###

# Get attendees for event
GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees